global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: order-service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]
        labels:
          application: 'Order Service Application'
  - job_name: inventory-service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]
        labels:
          application: 'Inventory Service Application'
  - job_name: history-service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: 'History Service Application'
  - job_name: api-gateway
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8765' ]
        labels:
          application: 'Api Gateway Application'
