spring:
  application:
    name: client-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/client-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
