spring:
  application:
    name: client-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/client-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    hostname: localhost
server:
  port: 0
