spring:
  devtools:
    restart:
      enabled: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    template:
      observation-enabled: true
  application:
    name: order-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    hostname: localhost
management:
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: 'order-service'
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
server:
  port: 8085
resilience4j:
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration:
          seconds: 5
  timelimiter:
    instances:
      inventory:
        timeout-duration:
          seconds: 3
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true