spring:
  application:
    name: inventory-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    hostname: localhost
server:
  port: 8084
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: inventory-service
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
